# ***********************
# plumber.R

library(recommenderlab)
library(dplyr)
library(readr)

# Debug
print(local_path)

#***********************
# storing and reading data ----
get_article_data <- function(){
  read_rds(paste0(local_path,"/articles.rds"))
}

store_user_ratings <- function(m){
  m %>% as("data.frame") %>% write_rds(paste0(local_path,"/ratings.rds"))
}

read_user_ratings <- function(){
  m <- read_rds(paste0(local_path,"/ratings.rds")) %>% as("realRatingMatrix")
}

#***********************
# initialization ----
possible_recommenders <- c("POPULAR", "IBCF", "UBCF", "SVD")
user_data <- tibble(userid = 0L, recommender = possible_recommenders[1])
articles <- get_article_data()



# ***********************
# helping functions -----


# create new rempty rating matrix
new_rating_matrix <- function(){
  entry <- data.frame(user = character(0L), item = character(0L), rating = numeric(0L), stringsAsFactors = F)
  entry %>% as("realRatingMatrix")
}


# add a rating to an existing rating matrix
add_rating <- function(m, user_id, item_id, rating){
  df <- m %>%  as("data.frame") 
  if(length(df) == 0){
    df <- data.frame(user = character(0L), item = character(0L), rating = numeric(0L), stringsAsFactors = F)
  }
  entry <- data.frame(user = user_id, item = item_id, rating = rating, stringsAsFactors = F)
  df %>% bind_rows(entry) %>% as("realRatingMatrix")
}




#***********************
#***********************
#
# API FUNCTIONS ----
#
#***********************

#' Register a User at the recommender system
#' @param participantID ID generated by Qualtrics
#' @param age Age of the participant
#' @param gender Gender of the participant
#' @get /register
#' @json
function(participantID, age, gender){
  # Create a new user object
  # Add user to the recommemnder
  
  print(paste(participantID, age, gender))
  
  "success"
}

#' Gets a recommendation for the specified recsys
#' @param participantID ID generated by Qualtrics
#' @param recsys the name for the recommender system 
#' @param iteration the number of recommended iterations
#' @get /getrecommendation
#' @json
function(participantID, recsys = "RANDOM", iteration){
  
  #debug
  #participantID <- "U11"
  #recsys <- "UBCF"
  m <- read_user_ratings()
  rec <- Recommender(m, method = recsys)
  
  if(participantID %in% as.list(rownames(m))){
    recom <- predict(rec, m[participantID,], n=1)
  } else {
    rec <- Recommender(m, method = "RERECOMMEND")
    recom <- predict(rec, m["DEMO",], n=1)
  }
  recs <- as(recom, "list")
  article_id <- recs[[1]] %>% as.numeric()
  
  #get first recommendation
  articles %>% filter(ID_Article %in% article_id)
}

#' Sends the rating for a given item by a user
#' @param participantID ID generated by Qualtrics
#' @param itemID ID of the recommended item
#' @param rating how was the item rated
#' @get /sendrecommendation
#' @json
function(participantID, itemID, rating){
  #itemID <- "7361"
  #rating <- 5
  m <- read_user_ratings()
  m <- m %>% add_rating(participantID, itemID, as.numeric(rating))
  store_user_ratings(m)
  
  #Add rating to the recommender system for the given user
  #Store changes in the db
  #update recommender 
  "success"
}


#' Plot out data from the iris dataset
#' @param spec If provided, filter the data to only this species (e.g. 'setosa')
#' @get /plot
#' @png
function(spec){
  m <- read_user_ratings()
  r_m <- normalize(m)
  getRatingMatrix(r_m)
  p <- image(r_m, main = "Normalized Ratings")
  print(p)
}


#' Test whether the service is alive
#' @get /alive
#' @json
alive <- function(){
  "Server is alive."
}
