# plumber.R

library(recommenderlab)
library(tidyverse)


possible_recommenders <- c("POPULAR", "IBCF")
user_data <- tibble(userid = 0L, recommender = possible_recommenders[1])

data(Jester5k)
set.seed(1234)
r <- sample(Jester5k, 5000)
r <- Recommender(Jester5k[1:1000], method = "UBCF")
getModel(r)$topN





#' Echo the parameter that was sent in
#' @param num number of jokes
#' @get /echo
#' @json
function(num = 3){
  recom <- predict(r, Jester5k[1001:1001], n=num)
  jokes <- as(recom, "list")
  jokelist <- JesterJokes[jokes[[1]]]
  
  list(headline="Joke", msg = jokelist)
}


#' Register a User at the recommender system
#' @param participantID ID generated by Qualtrics
#' @param age Age of the participant
#' @param gender Gender of the participant
#' @get /register
#' @json
function(participantID, age, gender){
  # Create a new user object
  # Add user to the recommemnder
  
  print(paste(participantID, age, gender))
  
  "success"
}

#' Gets a recommendation for the specified recsys
#' @param participantID ID generated by Qualtrics
#' @param recsys the name for the recommender system 
#' @param iteration the number of recommended iterations
#' @get /getrecommendation
#' @json
function(participantID, recsys, iteration){
  
}

#' Sends the rating for a given item by a user
#' @param participantID ID generated by Qualtrics
#' @param itemID ID of the recommended item
#' @param rating how was the item rated
#' @get /sendrecommendation
#' @json
function(participantID, itemID, rating){
  
  #Add rating to the recommender system for the given user
  #Store changes in the db
  #update recommender 
  "success"
}


#' Plot out data from the iris dataset
#' @param spec If provided, filter the data to only this species (e.g. 'setosa')
#' @get /plot
#' @png
function(spec){
  myData <- iris
  title <- "All Species"
  
  # Filter if the species was specified
  if (!missing(spec)){
    title <- paste0("Only the '", spec, "' Species")
    myData <- subset(iris, Species == spec)
  }
  
  plot(myData$Sepal.Length, myData$Petal.Length,
       main=title, xlab="Sepal Length", ylab="Petal Length")
}
